/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as HelpRouteImport } from './routes/help'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as PartnerRouteImport } from './routes/partner'
import { Route as PlansRouteImport } from './routes/plans'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProviderRouteImport } from './routes/provider'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as LaundryIndexRouteImport } from './routes/laundry/index'
import { Route as LaundryIdRouteImport } from './routes/laundry/$id'
import { Route as LaundryBookRouteImport } from './routes/laundry/book'
import { Route as TiffinIndexRouteImport } from './routes/tiffin/index'
import { Route as TiffinIdRouteImport } from './routes/tiffin/$id'
import { Route as TrackIdRouteImport } from './routes/track.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerRoute = PartnerRouteImport.update({
  id: '/partner',
  path: '/partner',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansRoute = PlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProviderRoute = ProviderRouteImport.update({
  id: '/provider',
  path: '/provider',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const LaundryIndexRoute = LaundryIndexRouteImport.update({
  id: '/laundry/',
  path: '/laundry/',
  getParentRoute: () => rootRouteImport,
} as any)
const LaundryIdRoute = LaundryIdRouteImport.update({
  id: '/laundry/$id',
  path: '/laundry/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LaundryBookRoute = LaundryBookRouteImport.update({
  id: '/laundry/book',
  path: '/laundry/book',
  getParentRoute: () => rootRouteImport,
} as any)
const TiffinIndexRoute = TiffinIndexRouteImport.update({
  id: '/tiffin/',
  path: '/tiffin/',
  getParentRoute: () => rootRouteImport,
} as any)
const TiffinIdRoute = TiffinIdRouteImport.update({
  id: '/tiffin/$id',
  path: '/tiffin/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackIdRoute = TrackIdRouteImport.update({
  id: '/track/$id',
  path: '/track/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/help': typeof HelpRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/orders': typeof OrdersRoute
  '/partner': typeof PartnerRoute
  '/plans': typeof PlansRoute
  '/privacy': typeof PrivacyRoute
  '/provider': typeof ProviderRoute
  '/register': typeof RegisterRoute
  '/terms': typeof TermsRoute
  '/laundry/$id': typeof LaundryIdRoute
  '/laundry/book': typeof LaundryBookRoute
  '/tiffin/$id': typeof TiffinIdRoute
  '/track/$id': typeof TrackIdRoute
  '/laundry/': typeof LaundryIndexRoute
  '/tiffin/': typeof TiffinIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/help': typeof HelpRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/orders': typeof OrdersRoute
  '/partner': typeof PartnerRoute
  '/plans': typeof PlansRoute
  '/privacy': typeof PrivacyRoute
  '/provider': typeof ProviderRoute
  '/register': typeof RegisterRoute
  '/terms': typeof TermsRoute
  '/laundry/$id': typeof LaundryIdRoute
  '/laundry/book': typeof LaundryBookRoute
  '/tiffin/$id': typeof TiffinIdRoute
  '/track/$id': typeof TrackIdRoute
  '/laundry': typeof LaundryIndexRoute
  '/tiffin': typeof TiffinIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/help': typeof HelpRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/orders': typeof OrdersRoute
  '/partner': typeof PartnerRoute
  '/plans': typeof PlansRoute
  '/privacy': typeof PrivacyRoute
  '/provider': typeof ProviderRoute
  '/register': typeof RegisterRoute
  '/terms': typeof TermsRoute
  '/laundry/$id': typeof LaundryIdRoute
  '/laundry/book': typeof LaundryBookRoute
  '/tiffin/$id': typeof TiffinIdRoute
  '/track/$id': typeof TrackIdRoute
  '/laundry/': typeof LaundryIndexRoute
  '/tiffin/': typeof TiffinIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/checkout'
    | '/contact'
    | '/dashboard'
    | '/help'
    | '/how-it-works'
    | '/login'
    | '/orders'
    | '/partner'
    | '/plans'
    | '/privacy'
    | '/provider'
    | '/register'
    | '/terms'
    | '/laundry/$id'
    | '/laundry/book'
    | '/tiffin/$id'
    | '/track/$id'
    | '/laundry/'
    | '/tiffin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/checkout'
    | '/contact'
    | '/dashboard'
    | '/help'
    | '/how-it-works'
    | '/login'
    | '/orders'
    | '/partner'
    | '/plans'
    | '/privacy'
    | '/provider'
    | '/register'
    | '/terms'
    | '/laundry/$id'
    | '/laundry/book'
    | '/tiffin/$id'
    | '/track/$id'
    | '/laundry'
    | '/tiffin'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/checkout'
    | '/contact'
    | '/dashboard'
    | '/help'
    | '/how-it-works'
    | '/login'
    | '/orders'
    | '/partner'
    | '/plans'
    | '/privacy'
    | '/provider'
    | '/register'
    | '/terms'
    | '/laundry/$id'
    | '/laundry/book'
    | '/tiffin/$id'
    | '/track/$id'
    | '/laundry/'
    | '/tiffin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  HelpRoute: typeof HelpRoute
  HowItWorksRoute: typeof HowItWorksRoute
  LoginRoute: typeof LoginRoute
  OrdersRoute: typeof OrdersRoute
  PartnerRoute: typeof PartnerRoute
  PlansRoute: typeof PlansRoute
  PrivacyRoute: typeof PrivacyRoute
  ProviderRoute: typeof ProviderRoute
  RegisterRoute: typeof RegisterRoute
  TermsRoute: typeof TermsRoute
  LaundryIdRoute: typeof LaundryIdRoute
  LaundryBookRoute: typeof LaundryBookRoute
  TiffinIdRoute: typeof TiffinIdRoute
  TrackIdRoute: typeof TrackIdRoute
  LaundryIndexRoute: typeof LaundryIndexRoute
  TiffinIndexRoute: typeof TiffinIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner': {
      id: '/partner'
      path: '/partner'
      fullPath: '/partner'
      preLoaderRoute: typeof PartnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans': {
      id: '/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof PlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/provider': {
      id: '/provider'
      path: '/provider'
      fullPath: '/provider'
      preLoaderRoute: typeof ProviderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/laundry/': {
      id: '/laundry/'
      path: '/laundry'
      fullPath: '/laundry/'
      preLoaderRoute: typeof LaundryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/laundry/$id': {
      id: '/laundry/$id'
      path: '/laundry/$id'
      fullPath: '/laundry/$id'
      preLoaderRoute: typeof LaundryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/laundry/book': {
      id: '/laundry/book'
      path: '/laundry/book'
      fullPath: '/laundry/book'
      preLoaderRoute: typeof LaundryBookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tiffin/': {
      id: '/tiffin/'
      path: '/tiffin'
      fullPath: '/tiffin/'
      preLoaderRoute: typeof TiffinIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tiffin/$id': {
      id: '/tiffin/$id'
      path: '/tiffin/$id'
      fullPath: '/tiffin/$id'
      preLoaderRoute: typeof TiffinIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track/$id': {
      id: '/track/$id'
      path: '/track/$id'
      fullPath: '/track/$id'
      preLoaderRoute: typeof TrackIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  HelpRoute: HelpRoute,
  HowItWorksRoute: HowItWorksRoute,
  LoginRoute: LoginRoute,
  OrdersRoute: OrdersRoute,
  PartnerRoute: PartnerRoute,
  PlansRoute: PlansRoute,
  PrivacyRoute: PrivacyRoute,
  ProviderRoute: ProviderRoute,
  RegisterRoute: RegisterRoute,
  TermsRoute: TermsRoute,
  LaundryIdRoute: LaundryIdRoute,
  LaundryBookRoute: LaundryBookRoute,
  TiffinIdRoute: TiffinIdRoute,
  TrackIdRoute: TrackIdRoute,
  LaundryIndexRoute: LaundryIndexRoute,
  TiffinIndexRoute: TiffinIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
