/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as PlansRouteImport } from './routes/plans'
import { Route as ProviderRouteImport } from './routes/provider'
import { Route as LaundryIndexRouteImport } from './routes/laundry/index'
import { Route as LaundryIdRouteImport } from './routes/laundry/$id'
import { Route as LaundryBookRouteImport } from './routes/laundry/book'
import { Route as TiffinIndexRouteImport } from './routes/tiffin/index'
import { Route as TiffinIdRouteImport } from './routes/tiffin/$id'
import { Route as TrackIdRouteImport } from './routes/track.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansRoute = PlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => rootRouteImport,
} as any)
const ProviderRoute = ProviderRouteImport.update({
  id: '/provider',
  path: '/provider',
  getParentRoute: () => rootRouteImport,
} as any)
const LaundryIndexRoute = LaundryIndexRouteImport.update({
  id: '/laundry/',
  path: '/laundry/',
  getParentRoute: () => rootRouteImport,
} as any)
const LaundryIdRoute = LaundryIdRouteImport.update({
  id: '/laundry/$id',
  path: '/laundry/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LaundryBookRoute = LaundryBookRouteImport.update({
  id: '/laundry/book',
  path: '/laundry/book',
  getParentRoute: () => rootRouteImport,
} as any)
const TiffinIndexRoute = TiffinIndexRouteImport.update({
  id: '/tiffin/',
  path: '/tiffin/',
  getParentRoute: () => rootRouteImport,
} as any)
const TiffinIdRoute = TiffinIdRouteImport.update({
  id: '/tiffin/$id',
  path: '/tiffin/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackIdRoute = TrackIdRouteImport.update({
  id: '/track/$id',
  path: '/track/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/checkout': typeof CheckoutRoute
  '/dashboard': typeof DashboardRoute
  '/orders': typeof OrdersRoute
  '/plans': typeof PlansRoute
  '/provider': typeof ProviderRoute
  '/laundry/$id': typeof LaundryIdRoute
  '/laundry/book': typeof LaundryBookRoute
  '/tiffin/$id': typeof TiffinIdRoute
  '/track/$id': typeof TrackIdRoute
  '/laundry/': typeof LaundryIndexRoute
  '/tiffin/': typeof TiffinIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/checkout': typeof CheckoutRoute
  '/dashboard': typeof DashboardRoute
  '/orders': typeof OrdersRoute
  '/plans': typeof PlansRoute
  '/provider': typeof ProviderRoute
  '/laundry/$id': typeof LaundryIdRoute
  '/laundry/book': typeof LaundryBookRoute
  '/tiffin/$id': typeof TiffinIdRoute
  '/track/$id': typeof TrackIdRoute
  '/laundry': typeof LaundryIndexRoute
  '/tiffin': typeof TiffinIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/checkout': typeof CheckoutRoute
  '/dashboard': typeof DashboardRoute
  '/orders': typeof OrdersRoute
  '/plans': typeof PlansRoute
  '/provider': typeof ProviderRoute
  '/laundry/$id': typeof LaundryIdRoute
  '/laundry/book': typeof LaundryBookRoute
  '/tiffin/$id': typeof TiffinIdRoute
  '/track/$id': typeof TrackIdRoute
  '/laundry/': typeof LaundryIndexRoute
  '/tiffin/': typeof TiffinIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/checkout'
    | '/dashboard'
    | '/orders'
    | '/plans'
    | '/provider'
    | '/laundry/$id'
    | '/laundry/book'
    | '/tiffin/$id'
    | '/track/$id'
    | '/laundry/'
    | '/tiffin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/checkout'
    | '/dashboard'
    | '/orders'
    | '/plans'
    | '/provider'
    | '/laundry/$id'
    | '/laundry/book'
    | '/tiffin/$id'
    | '/track/$id'
    | '/laundry'
    | '/tiffin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/checkout'
    | '/dashboard'
    | '/orders'
    | '/plans'
    | '/provider'
    | '/laundry/$id'
    | '/laundry/book'
    | '/tiffin/$id'
    | '/track/$id'
    | '/laundry/'
    | '/tiffin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CheckoutRoute: typeof CheckoutRoute
  DashboardRoute: typeof DashboardRoute
  OrdersRoute: typeof OrdersRoute
  PlansRoute: typeof PlansRoute
  ProviderRoute: typeof ProviderRoute
  LaundryIdRoute: typeof LaundryIdRoute
  LaundryBookRoute: typeof LaundryBookRoute
  TiffinIdRoute: typeof TiffinIdRoute
  TrackIdRoute: typeof TrackIdRoute
  LaundryIndexRoute: typeof LaundryIndexRoute
  TiffinIndexRoute: typeof TiffinIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans': {
      id: '/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof PlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/provider': {
      id: '/provider'
      path: '/provider'
      fullPath: '/provider'
      preLoaderRoute: typeof ProviderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/laundry/': {
      id: '/laundry/'
      path: '/laundry'
      fullPath: '/laundry/'
      preLoaderRoute: typeof LaundryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/laundry/$id': {
      id: '/laundry/$id'
      path: '/laundry/$id'
      fullPath: '/laundry/$id'
      preLoaderRoute: typeof LaundryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/laundry/book': {
      id: '/laundry/book'
      path: '/laundry/book'
      fullPath: '/laundry/book'
      preLoaderRoute: typeof LaundryBookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tiffin/': {
      id: '/tiffin/'
      path: '/tiffin'
      fullPath: '/tiffin/'
      preLoaderRoute: typeof TiffinIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tiffin/$id': {
      id: '/tiffin/$id'
      path: '/tiffin/$id'
      fullPath: '/tiffin/$id'
      preLoaderRoute: typeof TiffinIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track/$id': {
      id: '/track/$id'
      path: '/track/$id'
      fullPath: '/track/$id'
      preLoaderRoute: typeof TrackIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CheckoutRoute: CheckoutRoute,
  DashboardRoute: DashboardRoute,
  OrdersRoute: OrdersRoute,
  PlansRoute: PlansRoute,
  ProviderRoute: ProviderRoute,
  LaundryIdRoute: LaundryIdRoute,
  LaundryBookRoute: LaundryBookRoute,
  TiffinIdRoute: TiffinIdRoute,
  TrackIdRoute: TrackIdRoute,
  LaundryIndexRoute: LaundryIndexRoute,
  TiffinIndexRoute: TiffinIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
